# Generated by Django 5.0.6 on 2024-07-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='estudiante',
            new_name='Estudiante',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='cursos',
            new_name='Cursos',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='cursos',
            new_name='Cursos',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='curso',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='estudiante',
            new_name='Estudiante',
        ),
        migrations.RenameField(
            model_name='sesion',
            old_name='curso',
            new_name='Curso',
        ),
    ]
