# Generated by Django 5.0.6 on 2024-07-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='image',
        ),
    ]
