# Generated by Django 5.0.6 on 2024-07-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_curso_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='image',
            field=models.FileField(blank=True, upload_to='cursos_images/'),
        ),
    ]
