# Generated by Django 5.0.6 on 2024-07-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cursos',
        ),
        migrations.AddField(
            model_name='curso',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='cursos.categoria'),
        ),
    ]
