# Generated by Django 5.0.6 on 2024-07-09 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_escuelas_curso_escuela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='escuela',
        ),
        migrations.AddField(
            model_name='curso',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.escuelas'),
        ),
    ]
