# Generated by Django 5.0.6 on 2024-07-09 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_remove_curso_escuela_curso_escuela'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sisben',
            field=models.CharField(default='D4', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario_relacionado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_relacionado', to=settings.AUTH_USER_MODEL),
        ),
    ]
