# Generated by Django 5.0.6 on 2024-07-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_remove_estudiante_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
