# Generated by Django 5.0.6 on 2024-07-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_estudiante_usuario_relacionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario_relacionado',
        ),
    ]
