# Generated by Django 5.0.6 on 2024-07-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_estudiante_usuario_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='asistio',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
