# Generated by Django 5.0.6 on 2024-07-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_remove_sesion_asistio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='usuario_relacionado',
            new_name='usuario',
        ),
    ]
