# Generated by Django 5.0.6 on 2024-07-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_rename_usuario_relacionado_estudiante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('cc', 'Cedula de ciudadania'), ('ti', 'Tarjeta de identidad'), ('rc', 'Registro Civil'), ('ce', 'Cedula de Extranjería'), ('pep', 'Permiso especial de permanencia')], default='cc', max_length=255),
            preserve_default=False,
        ),
    ]
